language: r
sudo: false
cache: packages
r: 3.6.1
bioc_packages:
- S4Vectors
- GenomicRanges
- VariantAnnotation
- DNAcopy
- rtracklayer
before_install:
- curl -OL $URL
- mv jabba.tar.gz.gpg?dl=0 jabba.tar.gz.gpg
- echo $JAB | sudo gpg --passphrase-fd 0 jabba.tar.gz.gpg
- mkdir $HOME/my.cplex && tar -xvzf jabba.tar.gz --directory $HOME/my.cplex/
- curl -OL https://raw.githubusercontent.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
script: ./travis-tool.sh run_tests
after_failure:
- "./travis-tool.sh dump_logs"
after_success:
- travis_wait Rscript -e 'covr::codecov()'
env:
  global:
  - secure: W5ZnqwUcd23wTcVqAYXOz9wtn12vK5R5C1nj1YYIqZJqqAZgu7jgL5j98TSf3uW6AR8enPBQDjGzNAK63gin+fpLhq560G0Cb5akSPexPkrikX7hCsm0APzaNsDXtXGiUPSC7ZuTU7t59oE+Tk2tJEGNPMCRjypzt10a6J2r6HcpyGVv4tvWrZizh3H+7F/M2C0qoaa3crHNBv7fzEinuTOXg6cHz6oJjFBVOY+zOgzSfG62NWxW1NVRfdeF1WAWeWdRei1++9Eh/CRI2ag4/e91oBtSudme0NaVzUkbMmsrzlwmYkUFTllOQn/gc9qLgaEJlQsW0VHv81YzzZ6dC3j5PQfmqWSRzl6qi/Q5CBg/qkq8lKbe2pZqQvLAnnPiY4MP7shqd1w++wNRKj+tjssTxOcX2S7kUh7CyszhX8r7jA9jmLYi0tqEtP6NHx5lkOGoztT9x73e2cpz92i7NvxzsVBM23QvuD8auZCtmWXNpa5/RQJtixFYERtBpNSHVisq/Jg5VpALM8oOPNa0o77I5MTbthZxbZfkxVxldNkShCnwkou6gFmPz8eBOu0uYoLiS2pZPnec75Cx0LByRNCr6oyE2fLad8Q4ADU8rm4f7KelwzlPmw+lGW2+X8xFLZliUIIlJ/V6+Ss6DFxWmEbAIsUE35cz9ukdyax+uAc=
  - secure: Vi/3hhJxGsMnILhoZBAiqzLLufkYxyvd9xEpnTKnhVtps/SRj30KshRy2kM+PrtGSrGnlzIrnkncDjhyM1wVmJBR6hqfmbM9mpvaHyigfpa1sBsCwGEg7HGf5D0nII9CmY/bZwgLUZFAXHHNeCuvYSv95gJ+sXJBE40pYm4WOnjn+Feb2Ay/iMmmoWYyQRTpLSayRKRvs58q829Cy+X5DhB7UR81F8cKNh+a13TaWJ9jtwAAXPVGC+tc9A5+D8IjAA4DGrG9UeeVNDSq0ygO4KHSnRzpm2xx4Il3zgU3F2ayo3M3oXq9piXQ33/vgPnZrBRpGrIk/BXJTuTD1QyPe4j7o6gLdJ7ihX5YEgbfwIm14vfOuHkwuOS/quwnyWebfxFyHVWHE2gBbvyIakGkDWoO0m3Manv/s1R1d4nULJEGaOpPHqv4KmnEZdOkJ3xqt3HwjuFZm5aGg7jIKoEgYEUp48O2GVS79OYpuqzIVgtm9FD5g5SGiV5GzpPZTnNvv8Qh9rickgHNKuxNunvkc94v/f/DVqd3uDNSFbX4n2aJy8oeRFtAy253fcVMu7TgJlWZo+aHt+aEmlJ9HnJHFh1kMAscnnTcZpMneSd0yBIk7Nw0tMzpJeSgbO8rBDECEA2ZGaazNN/MfSqxX8kq3xMsSs3qFfYYOmoNfmVv51M=
  - secure: p4UXcB9d5974jheZBUvsJSZc7rtLvkn1PslWCR0a2d/H4warAFuaPr5nX23lq0ZDE7IT1FmQNVEkEbEalNYwXmLSOoNH4v8BnVEutMX3ypjNVT4xpSu/oOnFdrHy5oNyP9JanHwoxMiwmeGufZhMd/ZqsAbDgTL450dXwzlCfF0WxPxvidq9wvyrdYbLO2sihwesmZ3wfJxQn23r/x6yLSoTuKIUFaam+FPXghU3ROl3+raSkBC+FFz4yN5aOiDsnebRNjShI/9mJMEDWL1FvshJkqz+rQViINRCf8rk2RWgnls1PSfKeuzi5UAxeGriHwV2v1XWOq+/4ZPphm0vVenhM8Vp7pKScm+VQVM0/1+NTZ1aNMdIeTYVa/WgdHzZ12kuIEXs+5NGbKIIjIBljC4MpbDLa02LGpESgGgq3JV4LgqmN/88fBbiUSXSlgsAYvMgyvR2HobHI0pwrazremogKv6XgoSM8a8avFGHMUm4IIMMYnW0gLCrD6R3Ys30tAjyLTE/47Mt9D6yz5qBm5M1Qz1zo6wuIUG+xbtQ51n8IWyxy+WN8fzQTYm32ZPQ8jh2usPo02AUyK2VfWrB3WSJ/puqMad0u7qdYJB4HKqR7QEDvKKj/pskzAFkqoG8g4z6uGCdfJE/oRaVdEIDcW+FMJlTrMsHutYRZGmoFgY=
  - CPLEX_DIR=$HOME/my.cplex/
  - CPLEX_INCLUDE_PATH=$HOME/my.cplex/include
  - CPLEX_LIB_PATH=$HOME/my.cplex/lib
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran --no-examples"
  - _R_CHECK_TESTS_NLINES_=0
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE
  - _R_CHECK_FORCE_SUGGESTS_=false
